services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    WechatPayFaceToFaceBundle\DataFixtures\:
        resource: '../../DataFixtures'
        tags:
            - 'doctrine.fixture.orm'